-- 建立 numbers 資料表
CREATE TABLE IF NOT EXISTS public.numbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 註解：若要啟用 Realtime，請在 Supabase Dashboard 的 Table Editor 
-- 或 Database > Replication 頁面中將此資料表加入 'supabase_realtime' 發布 (Publication)。
-- SQL 指令：
-- ALTER PUBLICATION supabase_realtime ADD TABLE numbers;

-- RLS 建議：
-- 1. 啟用 RLS
-- ALTER TABLE numbers ENABLE ROW LEVEL SECURITY;
-- 2. 允許匿名使用者插入資料 (用於 index 頁面)
-- CREATE POLICY "Allow public insert" ON numbers FOR INSERT WITH CHECK (true);
-- 3. 允許匿名使用者讀取資料 (用於 admin 頁面)
-- CREATE POLICY "Allow public select" ON numbers FOR SELECT USING (true);
